### ISSUE TITLE
website stuck after navigating to 'Research Opportunities'

### ISSUE THREAD

**Issue by bch0w** [calum-chamberlain/calum-chamberlain.github.io#1]
Hi Calum! I was putzin' around your website (great photos!) and noticed that when you click on 'Research Opportunities', you can't navigate back to the rest of the website. 

Looks like the relative URLS get stuck in the student-projects.html page and it can't get back to index, e.g., clicking 'about me' after 'research opportunities' tries to navigate to student-projects.html#about.

Thought that might be of interest to you :smile:

**Comment by calum-chamberlain** [comment]
Thanks @bch0w! I will try to fix that... 

Hope you are going well - looking forward to that South Island velocity model some time :stuck_out_tongue:
